sudo: false
language: java
dist: trusty
jdk:
  - oraclejdk8
  - openjdk-ea
matrix:
  allow_failures:
    - jdk: openjdk-ea
cache:
  directories:
    - "$HOME/.m2"
install: "/bin/true"
addons:
  sonarcloud:
    organization: "lifemc"
    token:
      secure: $SONAR_TOKEN
script:
  - git fetch --unshallow --quiet; fi
  - mvn -Duser.name="Skript Team" -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Duser.language=en -Duser.country=US -Duser.timezone=Asia/Istanbul --batch-mode -e -B -DcompilerArgument=-O clean install package sonar:sonar
  - java -jar lib/proguard.jar @Skript.pro
