sudo: false
language: java
dist: xenial
jdk:
  - oraclejdk8
  - openjdk11
matrix:
  allow_failures:
    - jdk: openjdk-ea
cache:
  directories:
    - "$HOME/.m2"
install: "/bin/true"
script:
  - mvn --batch-mode -e -B -DcompilerArgument=-O clean install package
