sudo: false
language: java
install: true
dist: trusty
jdk:
  - oraclejdk8
  - openjdk-ea
matrix:
  fast_finish: true
  allow_failures:
    - jdk: openjdk-ea
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.sonar"
    - "$HOME/jvm"
addons:
  sonarcloud:
    organization: "lifemc"
    token:
      secure: $SONAR_TOKEN
notifications:
  email: false
script:
  - git fetch --unshallow --quiet
  - git fetch --no-tags https://github.com/LifeMC/LifeSkript +refs/heads/master:refs/remotes/origin/master
  - mvn -Duser.name="Skript Team" -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Duser.language=en -Duser.country=US -Duser.timezone=Asia/Istanbul --batch-mode -e -B -DcompilerArgument=-O clean org.jacoco:jacoco-maven-plugin:prepare-agent install package sonar:sonar
  - java -jar lib/proguard.jar @Skript.pro
