#
#   This file is part of Skript.
#
#  Skript is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Skript is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Skript. If not, see <https://www.gnu.org/licenses/>.
# 
# 
# Copyright 2011-2019 Peter Güttinger and contributors
# 

name: Skript

description: Customize Minecraft's mechanics with simple scripts written in plain English sentences.

authors: [Njol, Mirreski, LifeMCServer]
website: https://github.com/LifeMC/LifeSkript

main: ch.njol.skript.Skript

version: ${project.version}

commands:
  skript:
    description: Skript's main command. Type '/skript help' for more information.
    aliases: [sk]
    permission: skript.admin
    usage: /skript help

# Load Skript after some plugins just for safety and interactions with these plugins.
soft-depend: [Vault, WorldGuard, WorldEdit, SQLibrary, NoCheatPlus, IConomy, Residence, ChestShop, Factions, ASkyBlock, MotdManager, ServerListPlus, GriefPrevention, PreciousStones]

permissions:
  skript.*:
    default: false
    children:
      skript.effectcommands: true
      skript.admin: true
  skript.effectcommands:
    default: false
    description: Allows to use effects as commands, e.g. '!set health to 10'
  skript.admin:
    default: op
    description: Allows to use administrative commands and to recieve notifications of new versions.
