command /eval <text>:
	description: Evaluates the given effect.
	usage: /eval <effect>
	executable by: players and console
	permission: skript.eval
	permission message: &4No permission!
	trigger:
		execute arg-1
		if last execute state is false:
			send last execute errors to command sender # use command sender instead of player to be able to use as console.
		else:
			send "&aExecuted without errors!" to command sender
